# Generated by Django 5.0.2 on 2024-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('resume', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='campany_image',
            field=models.ImageField(upload_to='campanies/'),
        ),
    ]
